server:
  port: 8080
  servlet:
    context-path: /isp392
spring:
  datasource:
    url: jdbc:sqlserver://database.purintech.id.vn:1433;databaseName=ISP392_FOODSYSTEM;encrypt=true;trustServerCertificate=true;
    username: ispmaifa
    password: ispmaifa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

jwt:
  signerKey: fgSgZOIgNe6UNMGTaXNyQTMEIcx/cRzJxMXxFFu6npVmY6nfNM55d9UlAAU+ehbJ

